name: Publish to npm

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
        default: latest
  workflow_dispatch:
    inputs:
      tag:
        description: npm dist-tag
        required: true
        default: beta
        type: choice
        options:
          - beta
          - next
          - latest

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --tag ${{ inputs.tag || 'latest' }}
